-- MySQL Script generated by MySQL Workbench
-- Mon Mar 15 21:05:51 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema octopus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema octopus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `octopus` DEFAULT CHARACTER SET utf8 ;
USE `octopus` ;

-- -----------------------------------------------------
-- Table `octopus`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `octopus`.`utilisateur` (
  `id_utilisateur` INT NOT NULL,
  `nom_utilisateur` VARCHAR(30) NULL,
  `prenom_utilisateur` VARCHAR(30) NULL,
  `age` VARCHAR(10) NULL,
  `email` VARCHAR(45) NOT NULL,
  `sexe` CHAR(1) NULL,
  PRIMARY KEY (`id_utilisateur`),
  UNIQUE INDEX `id_utilisateur_UNIQUE` (`id_utilisateur` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `octopus`.`histoire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `octopus`.`histoire` (
  `id_histoire` INT NOT NULL,
  `site_web` VARCHAR(45) NOT NULL,
  `description_his` VARCHAR(45) NOT NULL,
  `titre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_histoire`),
  UNIQUE INDEX `id_histoire_UNIQUE` (`id_histoire` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `octopus`.`bourse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `octopus`.`bourse` (
  `id_bourse` INT NOT NULL,
  `nom_pays` VARCHAR(45) NOT NULL,
  `program` VARCHAR(200) NOT NULL,
  `exigence` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_bourse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `octopus`.`université`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `octopus`.`université` (
  `id_university` INT NOT NULL,
  `nom_university` VARCHAR(45) NOT NULL,
  `localisation` VARCHAR(45) NOT NULL,
  `site_web` VARCHAR(45) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `status` VARCHAR(10) NOT NULL,
  `rang` INT NOT NULL,
  `etudiant_internationaux` INT NOT NULL,
  `dispo_bourse` CHAR(3) NOT NULL,
  `ville_id_ville` INT NOT NULL,
  `ville_pays_id_pays` INT NOT NULL,
  `histoire_id_histoire` INT NOT NULL,
  `bourse_id_bourse` INT NOT NULL,
  `histoire_id_histoire1` INT NOT NULL,
  `bourse_id_bourse1` INT NOT NULL,
  PRIMARY KEY (`id_university`, `ville_id_ville`, `ville_pays_id_pays`, `histoire_id_histoire`, `bourse_id_bourse`, `histoire_id_histoire1`, `bourse_id_bourse1`),
  UNIQUE INDEX `id_university_UNIQUE` (`id_university` ASC) VISIBLE,
  INDEX `fk_université_histoire1_idx` (`histoire_id_histoire1` ASC) VISIBLE,
  INDEX `fk_université_bourse1_idx` (`bourse_id_bourse1` ASC) VISIBLE,
  CONSTRAINT `fk_université_histoire1`
    FOREIGN KEY (`histoire_id_histoire1`)
    REFERENCES `octopus`.`histoire` (`id_histoire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_université_bourse1`
    FOREIGN KEY (`bourse_id_bourse1`)
    REFERENCES `octopus`.`bourse` (`id_bourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `octopus`.`supermarket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `octopus`.`supermarket` (
  `id_supermarket` INT NOT NULL,
  `site_web_superm` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_supermarket`),
  UNIQUE INDEX `id_supermarket_UNIQUE` (`id_supermarket` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `octopus`.`hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `octopus`.`hospital` (
  `id_hospital` INT NOT NULL,
  `site_web_hospital` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `id_hospital_UNIQUE` (`id_hospital` ASC) VISIBLE,
  PRIMARY KEY (`id_hospital`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `octopus`.`restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `octopus`.`restaurant` (
  `id_restaurant` INT NOT NULL,
  `site_web_resto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_restaurant`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `octopus`.`coffee shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `octopus`.`coffee shop` (
  `id_coffee shop` INT NOT NULL,
  `site_web_coffeeshop` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_coffee shop`),
  UNIQUE INDEX `id_coffee shop_UNIQUE` (`id_coffee shop` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `octopus`.`ville`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `octopus`.`ville` (
  `id_ville` INT NOT NULL,
  `nom_ville` VARCHAR(45) NOT NULL,
  `pays_id_pays` INT NOT NULL,
  `supermarket_id_supermarket` INT NOT NULL,
  `hospital_id_hospital` INT NOT NULL,
  `restaurant_id_restaurant` INT NOT NULL,
  `coffee shop_id_coffee shop` INT NOT NULL,
  `université_id_university` INT NOT NULL,
  `université_ville_id_ville` INT NOT NULL,
  `université_ville_pays_id_pays` INT NOT NULL,
  `université_histoire_id_histoire` INT NOT NULL,
  `université_bourse_id_bourse` INT NOT NULL,
  `université_histoire_id_histoire1` INT NOT NULL,
  `université_bourse_id_bourse1` INT NOT NULL,
  PRIMARY KEY (`id_ville`, `pays_id_pays`, `supermarket_id_supermarket`, `hospital_id_hospital`, `restaurant_id_restaurant`, `coffee shop_id_coffee shop`, `université_id_university`, `université_ville_id_ville`, `université_ville_pays_id_pays`, `université_histoire_id_histoire`, `université_bourse_id_bourse`, `université_histoire_id_histoire1`, `université_bourse_id_bourse1`),
  UNIQUE INDEX `id_ville_UNIQUE` (`id_ville` ASC) VISIBLE,
  INDEX `fk_ville_supermarket1_idx` (`supermarket_id_supermarket` ASC) VISIBLE,
  INDEX `fk_ville_hospital1_idx` (`hospital_id_hospital` ASC) VISIBLE,
  INDEX `fk_ville_restaurant1_idx` (`restaurant_id_restaurant` ASC) VISIBLE,
  INDEX `fk_ville_coffee shop1_idx` (`coffee shop_id_coffee shop` ASC) VISIBLE,
  INDEX `fk_ville_université1_idx` (`université_id_university` ASC, `université_ville_id_ville` ASC, `université_ville_pays_id_pays` ASC, `université_histoire_id_histoire` ASC, `université_bourse_id_bourse` ASC, `université_histoire_id_histoire1` ASC, `université_bourse_id_bourse1` ASC) VISIBLE,
  CONSTRAINT `fk_ville_supermarket1`
    FOREIGN KEY (`supermarket_id_supermarket`)
    REFERENCES `octopus`.`supermarket` (`id_supermarket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ville_hospital1`
    FOREIGN KEY (`hospital_id_hospital`)
    REFERENCES `octopus`.`hospital` (`id_hospital`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ville_restaurant1`
    FOREIGN KEY (`restaurant_id_restaurant`)
    REFERENCES `octopus`.`restaurant` (`id_restaurant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ville_coffee shop1`
    FOREIGN KEY (`coffee shop_id_coffee shop`)
    REFERENCES `octopus`.`coffee shop` (`id_coffee shop`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ville_université1`
    FOREIGN KEY (`université_id_university` , `université_ville_id_ville` , `université_ville_pays_id_pays` , `université_histoire_id_histoire` , `université_bourse_id_bourse` , `université_histoire_id_histoire1` , `université_bourse_id_bourse1`)
    REFERENCES `octopus`.`université` (`id_university` , `ville_id_ville` , `ville_pays_id_pays` , `histoire_id_histoire` , `bourse_id_bourse` , `histoire_id_histoire1` , `bourse_id_bourse1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `octopus`.`pays`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `octopus`.`pays` (
  `id_pays` INT NOT NULL,
  `nom_pays` VARCHAR(45) NOT NULL,
  `ville_id_ville` INT NOT NULL,
  `ville_pays_id_pays` INT NOT NULL,
  PRIMARY KEY (`id_pays`, `ville_id_ville`, `ville_pays_id_pays`),
  UNIQUE INDEX `id_pays_UNIQUE` (`id_pays` ASC) VISIBLE,
  INDEX `fk_pays_ville1_idx` (`ville_id_ville` ASC, `ville_pays_id_pays` ASC) VISIBLE,
  CONSTRAINT `fk_pays_ville1`
    FOREIGN KEY (`ville_id_ville` , `ville_pays_id_pays`)
    REFERENCES `octopus`.`ville` (`id_ville` , `pays_id_pays`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `octopus`.`professeur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `octopus`.`professeur` (
  `id_professeur` INT NOT NULL,
  `nom_proffeseur` VARCHAR(45) NOT NULL,
  `prenom_professeur` VARCHAR(45) NOT NULL,
  `description_prof` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_professeur`),
  UNIQUE INDEX `id_professeur_UNIQUE` (`id_professeur` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `octopus`.`university_has_professeur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `octopus`.`university_has_professeur` (
  `university_id_university` INT NOT NULL,
  `university_ville_id_ville` INT NOT NULL,
  `university_ville_pays_id_pays` INT NOT NULL,
  `university_histoire_id_histoire` INT NOT NULL,
  `professeur_id_professeur` INT NOT NULL,
  PRIMARY KEY (`university_id_university`, `university_ville_id_ville`, `university_ville_pays_id_pays`, `university_histoire_id_histoire`, `professeur_id_professeur`),
  INDEX `fk_university_has_professeur_professeur1_idx` (`professeur_id_professeur` ASC) VISIBLE,
  INDEX `fk_university_has_professeur_university1_idx` (`university_id_university` ASC, `university_ville_id_ville` ASC, `university_ville_pays_id_pays` ASC, `university_histoire_id_histoire` ASC) VISIBLE,
  CONSTRAINT `fk_university_has_professeur_university1`
    FOREIGN KEY (`university_id_university` , `university_ville_id_ville` , `university_ville_pays_id_pays` , `university_histoire_id_histoire`)
    REFERENCES `octopus`.`université` (`id_university` , `ville_id_ville` , `ville_pays_id_pays` , `histoire_id_histoire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_university_has_professeur_professeur1`
    FOREIGN KEY (`professeur_id_professeur`)
    REFERENCES `octopus`.`professeur` (`id_professeur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `octopus`.`panier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `octopus`.`panier` (
  `university_id_university` INT NOT NULL,
  `university_ville_id_ville` INT NOT NULL,
  `university_ville_pays_id_pays` INT NOT NULL,
  `university_histoire_id_histoire` INT NOT NULL,
  `university_bourse_id_bourse` INT NOT NULL,
  `utilisateur_id_utilisateur` INT NOT NULL,
  PRIMARY KEY (`university_id_university`, `university_ville_id_ville`, `university_ville_pays_id_pays`, `university_histoire_id_histoire`, `university_bourse_id_bourse`, `utilisateur_id_utilisateur`),
  INDEX `fk_university_has_utilisateur_utilisateur1_idx` (`utilisateur_id_utilisateur` ASC) VISIBLE,
  INDEX `fk_university_has_utilisateur_university1_idx` (`university_id_university` ASC, `university_ville_id_ville` ASC, `university_ville_pays_id_pays` ASC, `university_histoire_id_histoire` ASC, `university_bourse_id_bourse` ASC) VISIBLE,
  CONSTRAINT `fk_university_has_utilisateur_university1`
    FOREIGN KEY (`university_id_university` , `university_ville_id_ville` , `university_ville_pays_id_pays` , `university_histoire_id_histoire` , `university_bourse_id_bourse`)
    REFERENCES `octopus`.`université` (`id_university` , `ville_id_ville` , `ville_pays_id_pays` , `histoire_id_histoire` , `bourse_id_bourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_university_has_utilisateur_utilisateur1`
    FOREIGN KEY (`utilisateur_id_utilisateur`)
    REFERENCES `octopus`.`utilisateur` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
